volumes:
  shared_uploads:


services:

  db:
    image: postgres:latest
    container_name: camagru_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - shared_uploads:/var/www/src/View/public/posts

  php:
    image: camagru
    container_name: camagru_php
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/
      - shared_uploads:/var/www/src/View/public/posts
    depends_on:
      - db
    env_file: .env
    develop:
        watch:
            -   action: sync
                path: .
                target: /var/www
            -   action: rebuild
                path: .

